### ISSUE TITLE
안드로이드 정기 스터디 1주차 과제

### ISSUE THREAD

**Issue by yonghanJu** [gdsc-konkuk/2023-gdsc-android-study-yonghaJu#1]
## 💡 과제 주제
- 안드로이드 기초: 뷰, 레이아웃, 엑티비티, 프래그먼트 등등 학습하고 마이페이지 만들어보자~

## 📝 TODO

- [x] 마이페이지 구현
- [x] 내 정보 수정 화면 구현
- [x] 마이페이지 -> 내 정보 수정 화면 연결
- [x] 닉네임 수정 칸에 빈칸을 입력 후 저장하기 버튼을 누른다면 토스트 메세지로 “ 닉네임은 빈칸일 수 없습니다.” 출력하기

## ⚙️ 비고
- 사항 없음
