### ISSUE TITLE
5주차 안드로이드 정기 스터디

### ISSUE THREAD

**Issue by yonghanJu** [gdsc-konkuk/2023-gdsc-android-study-yonghaJu#9]
## 💡 과제 주제
- 테스트 전략 수립 및 유닛 테스트

## 📝 TODO

- [x] 단위 테스트 대상 목록들 테스트 코드 
- [x] 테스트 결과 확인 ({pwd}/app/build/reports/tests/testReleaseUnitTest/index.html)
- [x] 테스트 코드 자동화

## ⚙️ 비고
- 사항 없음
